### ISSUE TITLE
Invalid Session Token

### ISSUE THREAD

**Issue by maz0uzi** [TheUnsocialEngineer/Antiland#9]
Hello,
I followed all the steps, but when I run the command I get an invalid session token. I'm using Chrome v128. I got a session token from the header tab which starts with r:xxxxxxxxxxx....
![image](https://github.com/user-attachments/assets/0ffb6ed1-80cd-45e0-bf49-ac7902a80e10)

**Comment by TheUnsocialEngineer** [comment]
Hi I have identified the issue and will be pushing a fix shortly

**Comment by maz0uzi** [comment]
> Hi I have identified the issue and will be pushing a fix shortly

Alright, thank you so much!

**Comment by TheUnsocialEngineer** [comment]
Version 0.99.2 is  now live and you can now log in :)

**Comment by maz0uzi** [comment]
It worked, thank you so much!
May I kindly request your email address or social media contacts?

**Comment by TheUnsocialEngineer** [comment]
You can reach out at eoka_official on discord or 404anarchynotfound on antiland

**Comment by maz0uzi** [comment]
I couldn't add you in Discord, here's mine mk70727.
Again, thank you so much for your time!

**Comment by maz0uzi** [comment]
Thank you so much for your time!
